#!/usr/bin/env python3
"""
Export crawled artifacts from Postgres into packages/db/seed.sql.

Workflow:
  1. Run crawlers until the index looks good (docker crawler or workers).
  2. python packages/db/export_seed_from_db.py
  3. Commit seed.sql — new clones get a fat index on first `docker compose up`.

Embeddings are omitted by default (smaller file; crawler/backfill fills them).
search_vector is rebuilt by the DB trigger on insert.

Usage:
  DATABASE_URL=postgresql://postgres:postgres@localhost:5433/build_radar \\
    python packages/db/export_seed_from_db.py

  python packages/db/export_seed_from_db.py --limit 200 --min-quality 50
  python packages/db/export_seed_from_db.py --with-embeddings  # large file
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path

try:
    import asyncpg
except ImportError:
    print("Install asyncpg: pip install asyncpg", file=sys.stderr)
    sys.exit(1)

ROOT = Path(__file__).resolve().parent
DEFAULT_OUT = ROOT / "seed.sql"


def sql_str(value: str | None) -> str:
    if value is None:
        return "null"
    return "'" + value.replace("'", "''") + "'"


def sql_text_array(values: list | None) -> str:
    if not values:
        return "'{}'"
    inner = ",".join(sql_str(str(v)) for v in values)
    return f"ARRAY[{inner}]::text[]"


def sql_jsonb(value) -> str:
    if value is None:
        return "'[]'::jsonb"
    if isinstance(value, str):
        try:
            value = json.loads(value)
        except json.JSONDecodeError:
            value = []
    return sql_str(json.dumps(value)) + "::jsonb"


def sql_ts(value) -> str:
    if value is None:
        return "now()"
    if isinstance(value, datetime):
        return f"'{value.isoformat()}'::timestamptz"
    return f"'{value}'::timestamptz"


def sql_vector(embedding) -> str:
    if embedding is None:
        return "null"
    # asyncpg may return str like '[0.1,...]'
    s = str(embedding).strip()
    if not s.startswith("["):
        return "null"
    return f"'{s}'::vector"


async def export(args: argparse.Namespace) -> int:
    dsn = os.getenv("DATABASE_URL", "postgresql://postgres:postgres@localhost:5433/build_radar")
    dsn = dsn.replace("postgresql+asyncpg://", "postgresql://")

    conn = await asyncpg.connect(dsn)
    try:
        count = await conn.fetchval("SELECT COUNT(*)::int FROM artifacts")
        query = """
            SELECT *
            FROM artifacts
            WHERE ($1::float IS NULL OR quality_score >= $1)
            ORDER BY quality_score DESC NULLS LAST, remixability_score DESC NULLS LAST
            LIMIT $2
        """
        rows = await conn.fetch(query, args.min_quality, args.limit)
    finally:
        await conn.close()

    out = DEFAULT_OUT if args.output == "-" else Path(args.output)
    lines: list[str] = [
        "-- Trove seed data (generated by export_seed_from_db.py)",
        f"-- Exported {len(rows)} of {count} artifacts from the live database.",
        "-- Embeddings: "
        + ("included" if args.with_embeddings else "NULL — run backfill or crawler after seed"),
        "-- search_vector is populated by trigger on insert.",
        "",
        "insert into profiles (username, display_name, bio, github_url, website_url, credibility_score)",
        "values",
        "  ('buildradar', 'Trove', 'Official seed account.', 'https://github.com/buildradar', null, 50),",
        "  ('vibecoder', 'Vibe Coder', 'Ships weekend AI apps.', null, null, 20)",
        "on conflict (username) do nothing;",
        "",
        "insert into artifacts (",
        "  title, slug, source_type, artifact_type, source_url, canonical_url,",
        "  author_name, author_url, summary, what_it_helps_build, technical_core,",
        "  practical_use_case, how_to_remix, implementation_steps, setup_commands,",
        "  tags, domains, tools, languages, frameworks, apis, models,",
        "  has_code, has_demo, has_docs, has_paper, has_license, license,",
        "  difficulty, estimated_time_to_integrate, published_at,",
        "  quality_score, remixability_score, applicability_score,",
        "  underground_score, hype_risk_score, popularity_score",
        + (", embedding" if args.with_embeddings else "")
        + ")",
        "values",
    ]

    value_blocks: list[str] = []
    for i, r in enumerate(rows, 1):
        cols = [
            sql_str(r["title"]),
            sql_str(r["slug"]),
            sql_str(r["source_type"]),
            sql_str(r["artifact_type"]),
            sql_str(r["source_url"]),
            sql_str(r["canonical_url"]),
            sql_str(r["author_name"]),
            sql_str(r["author_url"]),
            sql_str(r["summary"]),
            sql_str(r["what_it_helps_build"]),
            sql_str(r["technical_core"]),
            sql_str(r["practical_use_case"]),
            sql_str(r["how_to_remix"]),
            sql_jsonb(r["implementation_steps"]),
            sql_jsonb(r["setup_commands"]),
            sql_text_array(list(r["tags"] or [])),
            sql_text_array(list(r["domains"] or [])),
            sql_text_array(list(r["tools"] or [])),
            sql_text_array(list(r["languages"] or [])),
            sql_text_array(list(r["frameworks"] or [])),
            sql_text_array(list(r["apis"] or [])),
            sql_text_array(list(r["models"] or [])),
            "true" if r["has_code"] else "false",
            "true" if r["has_demo"] else "false",
            "true" if r["has_docs"] else "false",
            "true" if r["has_paper"] else "false",
            "true" if r["has_license"] else "false",
            sql_str(r["license"]),
            sql_str(r["difficulty"] or "unknown"),
            sql_str(r["estimated_time_to_integrate"]),
            sql_ts(r["published_at"]),
            str(float(r["quality_score"] or 0)),
            str(float(r["remixability_score"] or 0)),
            str(float(r["applicability_score"] or 0)),
            str(float(r["underground_score"] or 0)),
            str(float(r["hype_risk_score"] or 0)),
            str(float(r["popularity_score"] or 0)),
        ]
        if args.with_embeddings:
            cols.append(sql_vector(r["embedding"]))
        block = f"-- {i}. {r['title'][:60]}\n(\n  " + ",\n  ".join(cols) + "\n)"
        value_blocks.append(block)

    if not value_blocks:
        print("No rows matched — nothing written.", file=sys.stderr)
        return 1

    lines.append(",\n\n".join(value_blocks))
    lines.append("\non conflict (canonical_url) do nothing;\n")

    text = "\n".join(lines)
    if args.output == "-":
        sys.stdout.write(text)
    else:
        out.write_text(text, encoding="utf-8")
        print(f"Wrote {len(rows)} artifacts to {out} ({len(text) // 1024} KB)")
    return 0


def main() -> None:
    p = argparse.ArgumentParser(description="Export DB artifacts to seed.sql")
    p.add_argument("--output", "-o", default=str(DEFAULT_OUT), help="Output path or - for stdout")
    p.add_argument("--limit", type=int, default=300, help="Max artifacts to export")
    p.add_argument("--min-quality", type=float, default=None, help="Minimum quality_score")
    p.add_argument("--with-embeddings", action="store_true", help="Include vector(384) column (large)")
    args = p.parse_args()

    import asyncio

    raise SystemExit(asyncio.run(export(args)))


if __name__ == "__main__":
    main()
